system_name: quadrotor_2d
modality: vision
drone_dim: 2
num_views: 1
z_dynamics:
  model: linear
  z_dim: 10
  structured_AB: true
  affine_term: false
dt: 0.05

auto_encoder:
  include_state_in_z: false
  multi_view: false
  control_inputs: false
  H: 128
  W: 128
  CNN:
    encoder:
      num_in_channels: 2
      out_planes:
      - 28
      - 48
      - 64
      - 48
      - 28
      strides:
      - 2
      - 2
      - 2
      - 2
      - 2
      n_split_layers: 0
    decoder:
      num_out_channels: 1
      out_planes:
      - 28
      - 48
      - 64
      - 48
      - 28
      strides:
      - 2
      - 2
      - 2
      - 2
      - 2
  MLP:
    num_hidden_layers: 2
    hidden_dims:
    - 256
    - 192
  activation: relu
