drone_dim: 3
dataloader:
  batch_size: 32
  num_workers: 2

postprocessing:
  ds_step: 10
  smooth_window: 10
  delay: 0

train:
  num_steps_loaded: 251
  num_steps_pred: 251

val_datasets:
  - split: "val_1"
    name: "short_horizon"
    num_steps_loaded: 251
    num_steps_pred: 251

  - split: "val_2"
    name: "long_horizon"
    num_steps_loaded: 251
    num_steps_pred: 251

scaler:
  scale_x: false
  scale_u: true
  center: true
  mean_x: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
  mean_u: [0.28, 0, 0, 0]