system_name: quadrotor_2d
modality: sensor
drone_dim: 2
dataloader:
  batch_size: 128
  num_workers: 2
postprocessing:
  ds_step: 10
  smooth_window: 10
  delay: 0
train:
  num_traj_loaded: 3000
  num_steps_loaded: 300
  num_steps_pred: 50
val_datasets:
- split: val_1
  name: short_horizon
  num_traj_loaded: 200
  num_steps_loaded: 300
  num_steps_pred: 50
- split: val_2
  name: long_horizon
  num_traj_loaded: 200
  num_steps_loaded: 300
  num_steps_pred: 100
scaler:
  scale_x: true
  scale_u: true
  center: true
  mean_x:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  mean_u:
  - 0.26487
  - 0
