system_name: quadrotor_2d
modality: vision
drone_dim: 2
resolution: 128
dataloader:
  batch_size: 32
  num_workers: 2
postprocessing:
  ds_step: 1
  smooth_window: 1
  delay: 1
train:
  num_traj_loaded: 100
  num_steps_loaded: 251
  num_steps_pred: 50
val_datasets:
- split: val_1
  name: short_horizon
  num_traj_loaded: 50
  num_steps_loaded: 251
  num_steps_pred: 50
- split: val_2
  name: long_horizon
  num_traj_loaded: 50
  num_steps_loaded: 251
  num_steps_pred: 50
scaler:
  scale_x: false
  scale_u: true
  center: true
  mean_x:
  - 0
  - 0
  - 0
  - 0
  - 0
  - 0
  mean_u:
  - 0.26487
  - 0
