model_registry:
  "19":
    model_stamp: "bilin_2_2026-02-10_17-03-40"
    epoch: 310
    run_status: "final"
    drone_dim: 2
    best_simulations:
      open_loop:
        setpoint_tracking: "..."
        trajectory_tracking: "..."
      closed_loop:
        setpoint_tracking: "..."
        trajectory_tracking: "..."
  "20":
    model_stamp: "lin_2_2026-02-10_17-03-39"
    epoch: 300
    run_status: "final"
    drone_dim: 2
    best_simulations:
      open_loop:
        setpoint_tracking: "..."
        trajectory_tracking: "..."
      closed_loop:
        setpoint_tracking: "2026-02-25_17-00-15"
        trajectory_tracking: "2026-02-25_18-54-25"
  "21":
    model_stamp: "bilin_6_2026-02-16_13-28-57"
    epoch: 300
    run_status: "final"
    drone_dim: 2
    best_simulations:
      open_loop:
        setpoint_tracking: "..."
        trajectory_tracking: "..."
      closed_loop:
        setpoint_tracking: "2026-02-25_17-22-08"
        trajectory_tracking: "2026-02-25_18-51-28"
  "52":
    model_stamp: "lin_2_2026-03-16_10-29-55"
    epoch: 460
    run_status: "final"
    drone_dim: 3
    best_simulations:
      open_loop:
        setpoint_tracking: "2026-03-16_18-02-44"
        trajectory_tracking: "..."
      closed_loop:
        setpoint_tracking: "..."
        trajectory_tracking: "..."
  "53":
    model_stamp: "bilin_2_2026-03-16_17-48-46"
    epoch: 760
    run_status: "final"
    drone_dim: 3
    best_simulations:
      open_loop:
        setpoint_tracking: "2026-03-17_10-12-25"
        trajectory_tracking: "..."
      closed_loop:
        setpoint_tracking: "..."
        trajectory_tracking: "..."