seed: 1

simulation:
  dt: 0.001
  t_sim: 3.0

trajectory_generation:
  reference_bounds:
    x_max: 0.5
    y_max: 0.5
    z_max: 0.5

  initial_state_bounds:
    x_max: 0.5
    y_max: 0.5
    z_max: 0.5
    angle_max: 0.0

  reference_time_constants:
    tau_min: 0.05
    tau_max: 0.4

  options:
    only_aggressive: false
    init_angles_to_zero: false

splits:
  train:
    num_traj: 10
  val_1:
    num_traj: 10
  val_2:
    num_traj: 10