drone_dim: 2
closed_loop_every: 0
closed_loop_replay_enabled: false
num_epochs: 1200
checkpoint_every: 10
loss_weights: {y_pred: 250.0, y_rec: 40.0, z: 5.0, c: 0.4, a: 0.05}
bilin_reg: false
optimizer:
  lr:
    ab: 0.001
    ae: 0.001
  weight_decay: {ae: 8.0e-05, ab: 8.0e-05}
lr_decay: 0.996
curriculum:
  phase_epoch_triggers: [ 2, 75, 100 ]
  ramp_duration: 10