system_name: quadrotor_3d
modality: sensor
controller_type: kmpc
dt: 0.01
num_steps_horizon: 40

control_type: mpc
constraints:
  use_inputs_constraints: false
  force_limits:
  - 0
  - 1.2
  torque_limits:
  - -1
  - 1

cost:
  mode: state_in_z
  R:
  - 0.01
  - 0.01
  - 0.01
  - 0.01
  S:
  - 0.05
  - 0.05
  - 0.05
  - 0.05
  Q_state: 2
  P_state: 2

solver_options_profile: bilinear_latent_medium
